name: Ollivanders
version: '${project.version}'
main: mintychochip.ollivanders.Ollivanders
api-version: '1.20'
commands:
  component:
    description: wadwd
  wand:
    description: spawns a wand
  book:
    description: gives book
depend: [Genesis]